# Generated by Django 2.2.4 on 2019-08-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Name')),
                ('image', models.ImageField(upload_to='myimage/files', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create at')),
            ],
            options={
                'verbose_name': 'My Image',
                'verbose_name_plural': 'My Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
