# Generated by Django 2.2.4 on 2019-08-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80, unique=True, verbose_name='Name')),
                ('file', models.FileField(upload_to='myfile/files', verbose_name='Image')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
