# Generated by Django 2.2.4 on 2019-08-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='file',
            field=models.FileField(upload_to='myfile/files', verbose_name='Image'),
        ),
    ]
