# Generated by Django 2.2.4 on 2019-08-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfile', '0002_auto_20190822_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='description',
            field=models.CharField(max_length=80, verbose_name='Name'),
        ),
    ]
