# Generated by Django 2.2.4 on 2019-08-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfile', '0003_auto_20190822_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myfile',
            options={'ordering': ['-created_at'], 'verbose_name': 'My File', 'verbose_name_plural': 'My Files'},
        ),
        migrations.RenameField(
            model_name='myfile',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
